### ISSUE TITLE
Tenant Authorization in API Gateway

### ISSUE THREAD

**Issue by aedelmann** [eclipse/vorto#1087]
All resources belong to a specific tenant. This owning tenant id will be included in each request as part of the URL.
Vorto needs to validate that a user or service requesting a resource from Vorto is authorized to access this resource by validating that the owning tenant id from the request header is contained in the tid claim of the JWT.
If this is not the case the request is denied with status code 401.

**Confirmations:**
- Tenant Validation in API Gateway before dispatching request to Repository Service 
- REST API api/v1/* is  exposed by API gateway and included in the validation
- Support for following environments:

**Single Tenant (for e.g. Vorto Sandbox Setup) **
- No active Tenant Validation Check

**Multiple Tenant**
- Only requests with a JWT containing the owning tenant id are granted access to a resource

**Comment by erlemantos** [comment]
I have several questions:

1. "This owning tenant id will be included in each request as part of the URL" - This seems unnecessary. Each resources (I assume this means the model) has an author, and each author, presumably, belongs to a tenant. We can check the owning tenant by checking who the author is. In the case where the tenancy concept is directly linked to the model, and not the user who created that model, then somehow we will still be embedding the tenant information with the model (as a metadata, just like vorto:author) , and we can still check who the tenant is for the model without the need for embedding the tenant id in the URL.

Embedding the tenant Id in the URL is only necessary if we have separate storage for models for different tenants. E.g if we need to construct different database connection strings per tenant. 
Or if we redesign our model storage to include the tenant information in the tree. E.g <root>/tenant/<namespace>.../name/<etc ...>

I'm not really fond of including the tenant in the URL per API because we will be breaking compatibility with all existing applications that use the Vorto REST API directly.
