### ISSUE TITLE
A user can add / remove attachment web links for model versions.

### ISSUE THREAD

**Issue by aedelmann** [eclipse/vorto#1099]
Confirmations
- Shows a list of links to other resources for a model in the model details view
- Add resource link (only for model owner), who can specify a Web Link address, pointing to an additional document. The link is then shown as part of the link list , see point 1.
- Web link address must be a URL (supported linked documents are images, pdf, html)
- Model Owner can remove a web link

**Comment by mena-bosch** [comment]
@kolotu changeset on branch 1099 is good but doesn't allow sysadmins to manipulate links in models outside namespaces where they have the required role. 
I am fixing the UI side of this in #2599 since the change set is minimal and "compatible" albeit extraneous to #2599, but this will also require a change in the back-end, lets manipulating the links as sysadmin  fails in there.

**Comment by kolotu** [comment]
I was not able to reproduce that behaviour on the 1099 branch - it's probably some merging aftermath.
