### ISSUE TITLE
Example of modbus enabled device

### ISSUE THREAD

**Issue by splatch** [eclipse/vorto#1471]
Modbus is kind of protocol which requires a valid description of devices upfront. Is there any example use for Vorto as metadata/description driver to define modbus devices and their registries?

**Comment by erlemantos** [comment]
Hi. For now, no. We don't have any examples for Vorto. However, we are gonna take a look into that.

**Comment by aedelmann** [comment]
Hi @splatch 
This kind of modbus meta data can be added in the Repository as Vorto Mapping files under a specific target platform key. When you access the Vorto Repository REST content API, you would retrieve the function block and modebus meta-data in order to process it at runtime or in your code generator, e.g. to create modebus specific source code for devices. Sadly we do not have much documentation for usage of mappings yet. We are still working on this to improve.  We can provide some for you to get started with mappings. Would that help ?

**Comment by splatch** [comment]
> This kind of modbus meta data can be added in the Repository as Vorto Mapping files under a specific target platform key. When you access the Vorto Repository REST content API, you would retrieve the function block and modebus meta-data in order to process it at runtime or in your code generator, e.g. to create modebus specific source code for devices.
That's perfectly fine - I see that Vorto model describes device at high level from which you could also attach extra metadata for various transport layers. Many of devices I was playing lately can be equipped with various "transport" gateways such modbus or M-Bus. While both ways to talk to device are fundamentally different, they provide the same data.

> Sadly we do not have much documentation for usage of mappings yet. We are still working on this to improve. We can provide some for you to get started with mappings. Would that help ?
Yes, that would definitely help as I am completely new to Vorto ecosystem. I been trying to fetch this information (and missed it) for a while. Any examples in this area will be extremely helpful.

**Comment by aedelmann** [comment]
Hi @splatch 
I created a follow up issue to give a little better documentation on the mapping topic: https://github.com/eclipse/vorto/issues/1535
Feel free to comment on this. 
Would that help u for your use case then ? If so, I would close this issue. U can track the other more concrete topic.

**Comment by splatch** [comment]
@aedelmann Sure, lets track actionable items. I will subscribe to #1535 notifications instead.
