### ISSUE TITLE
TravisCi build failed due to SonarCloud integration 

### ISSUE THREAD

**Issue by vlvanchin** [eclipse/vorto#1502]
Problem: PR are not possible due to the failure of SonarCloud integration.

Actual outcome:
- .travisci fails due to "error: failed to connect to localhost:9000"

Expected outcom:
- get the Sonarcloud to work without failure

**Comment by aedelmann** [comment]
Hi @vlvanchin 
This problem only occurs for external Pull Requests because these external Pull Requests do not have the permission to connect to the sonar cloud. 

I will change the .travis-ci.yml to only execute the sonarqube coverage for non Pull Requests, which means after the code has been merged into development. It is kind of late but would work for now.
Any other suggestion ?

**Comment by aedelmann** [comment]
I fixed the problem with external PR. Like I said , it skips sonarcloud report upon PR but it still executes on dev branch once merged.
