### ISSUE TITLE
Getting Started references deprecated Vorto Eclipse IDE

### ISSUE THREAD

**Issue by andrew-from-pretoria** [eclipse/vorto#1635]
The Getting Started instructions at https://github.com/eclipse/vorto/blob/master/docs/gettingstarted.md includes the deprecated Vorto Eclipse IDE.

Where to find the problem:
Scroll down to the text
"Use Vorto Eclipse IDE to describe a device"

The problem:
The Vorto Eclipse IDE has been deprecated ( https://github.com/eclipse/vorto/blob/master/docs/release-notes.md ).

Suggested solution: 
Replace this with a reference to the Vorto cloud-based editor.

**Comment by erlemantos** [comment]
Thanks for pointing this out. We will fix it.

**Comment by aedelmann** [comment]
hi Andrew. Vorto Supports both cloud and eclipse toolset. As stated in the getting started.

**Comment by andrew-from-pretoria** [comment]
Hi Aedelmann. 

The release notes state that Vorto Eclipse Toolset is no longer supported since 0.10: 

"Deprecation - The Eclipse Vorto IoT Toolset Plugins are no longer supported. Instead you can simply use the Cloud-based Editors in the Vorto Repository." ( ref https://github.com/eclipse/vorto/blob/master/docs/release-notes.md )

Am I missing something? If so, please correct me since I've opened a number of issues based on this statement and will have to close/delete them if so.

Thanks

**Comment by aedelmann** [comment]
Well the eclipse based vorto IoT toolset is deprecated which comprised a IoT eclipse perspective that connects to vorto repository etc. 
Since 0.10 we are providing just simple eclipse plugins for the Vorto DSL editor. Which u can use to create Vorto models with autocomplete functionality. It is not as rich in functionality As the deprecated version. 
So either u use the cloud based editors or these eclipse plugins. 
The reason we deprecated the IoT Vorto eclipse toolset is because we primarily want to provide cloud tooling for the ease of model creation.

**Comment by andrew-from-pretoria** [comment]
Thank you for the clarification. :-)
