### ISSUE TITLE
Warn user "Your session is about to expire. You want to continue?"

### ISSUE THREAD

**Issue by aedelmann** [eclipse/vorto#1735]
Why?
When users are using the Vorto Repository particularly when editing models or creating mapping specifications, hardly any backend communication is done. This could potentially lead to session time outs when they make a backend request after such a long period of time, which discards users hard work. 

Solution:
- Sending of frequent heart-beats to backend
- ??

**Comment by kolotu** [comment]
I'll look into this one

**Comment by kolotu** [comment]
My idea for this issue is to create a new AngularJS service that sets a timeout to 5 minutes before the session expires. After that timeout expired a warning will be displayed to the user with a countdown and a button to extend the session.
I'm currently looking into a way to query the session timeout from the backend, so if the configuration there changes, the change will also be reflected in the UI.
