### ISSUE TITLE
Registered third party generator plugins display with their ID only

### ISSUE THREAD

**Issue by w4tsn** [eclipse/vorto#1988]
Since there is no issue for this small bug - here it is.

When registering a third party plugin with ditto it's displayed on the Plugins Overview Page and on single model pages only with it's bare ID instead of it's display name.

**Comment by kolotu** [comment]
Hi @w4tsn,

Could you please provide more context? Does this relate to the Ditto Generator?

**Comment by w4tsn** [comment]
I've setup the ditto generator as a docker container using the APIv1 approach from the examples with the APIv2 Java-Adapter. The plugin is specified in the vorto configuration `PLUGINS` variable. The code is in https://github.com/w4tsn/vorto-ditto-skeleton-generator

I'm running vorto 0.12.2 and the generator is build against 0.11.3

**Comment by kolotu** [comment]
@w4tsn I've briefly looked into your project, but I think what you are referring to, is that for generators in the generator-runner, no images are shown and also parts of the UI template are missing. 
This is indeed currently not implemented and the behaviour is in fact different from the generators running as AWS lambdas. We are evaluating, whether it still makes sense to maintain the generator-runner, since it is effectively handling requests differently, therefore we are currently not planning new implementations in the generator-runner. 

Have you tried using the AWS SAM Local tools for running your generator? There is a manual on how to use that for running generators here: https://github.com/eclipse/vorto/blob/development/generators/generator-lambda/Readme.md

Also maybe you can use our provided Eclipse Ditto Generator, which now has a new option to retrieve the Thing JSON, which is documented here: 
https://github.com/eclipse/vorto/blob/development/generators/generator-eclipseditto/Readme.md

The changes in the Eclipse Ditto Generator are currently on the development branch, but the next release will happen this month and then it will also be available on the master branch and the released JAR.

**Comment by w4tsn** [comment]
@kolotu Thanks for looking into this.

I've not yet tried the AWS Runner. Since there is also a local runtime toolkit I'll check this out. Indeed this sounds sufficient and I don't see a point in maintaining the generator-runner, except the fact that it is dependant on AWS tech. Since you can run it locally without the need of using the AWS Cloud that's fine with me.

The additions in the Ditto Generator are most welcome, thanks for the hint!

IMO you may close this as wontfix.

**Comment by kolotu** [comment]
@w4tsn thanks, if you do get the chance to try the AWS Runner and you discover any issues with our generators in that toolkit, we are happy to get your feedback. 
I'll close this issue then.
