### ISSUE TITLE
List of Vorto Function Blocks in Info Model Creation wizard shows all released Function Blocks

### ISSUE THREAD

**Issue by aedelmann** [eclipse/vorto#2137]
Steps:
1) Log in to Repository
2) Create Model and choose "Inforamtion Model"
2.1) In Semantic Abstract dialog, open the drop down of Function Blocks
Expected: Only released Function Blocks of namespace 'org.eclipse.vorto.*' are displayed and selectable
Actual: List displays released Function Blocks of any namespace

**Comment by aedelmann** [comment]
Side note:
1) Remove internal REST Endoint ../released in backend
2) Change Javascript to re-use the existing /api/1/search Rest Endpoint with the following search expression

```state:Released namespace:org.eclipse.vorto.* type:Functionblock```

**Comment by mena-bosch** [comment]
Thanks for the thorough specs on this one @aedelmann . Taking this for myself and starting soon.

**Comment by mena-bosch** [comment]
> Thanks for the thorough specs on this one @aedelmann . Taking this for myself and starting soon.

"starting soon" --> actually this bears waiting for the [search feature](https://github.com/eclipse/vorto/pull/2136) to be merged, so we can leverage the full tags.

**Comment by aedelmann** [comment]
@mena-bosch You are right. I will merge your PR, once all the checks are done :)

**Comment by mena-bosch** [comment]
> @mena-bosch You are right. I will merge your PR, once all the checks are done :)

Cool. I had to push again just now because I stupidly left one of the two malformed links out, but am hoping this is the last bit. 

After that, the one thing we may want to do is to recreate the index on the dev machine first, to verify it works as expected.
This is a crucial step in my opinion, otherwise the search will not work as expected due to the schema changes (namely, the few "key to text" type changes). 
If no issue there, we can proceed with prod in time.

**Comment by aedelmann** [comment]
Good point: Can we add this to the migration guide 0.12.x -> 1.0 ? 
@somesh-kumar : We need to mention the needed changes, with the introduction of mode shape5 there as well.

**Comment by mena-bosch** [comment]
> Good point: Can we add this to the migration guide 0.12.x -> 1.0 ?
> @somesh-kumar : We need to mention the needed changes, with the introduction of mode shape5 there as well.

@aedelmann Thanks for mentioning this. Having a look at the existing 0.11 guide now. I will probably have questions for you e.g. tomorrow. 
Something you can probably answer right away if you're still up: do we want the version change and addendum to migration_0.11.md to be part of the change set for the feature itself, i.e. same branch, or do we scope it to a separate one?

**Comment by mena-bosch** [comment]
@aedelmann nearly done here. 

Suspect we eliminate the other endpoint ("/public") too, and therefore the entire the controller, so that public models for tenant are also directly searched from angular. As I recall, tenant == namespace so I'd just need to call the search with 'namespace:'+tenant.defaultNamespace+'visibility:public' in angular.

I would rather do this in a new task for cleanliness, assuming you agree with the reasoning above.

**Comment by aedelmann** [comment]
Agreed :)

**Comment by mena-bosch** [comment]
> Agreed :)

Geez you're _still_ up?! :muscle:

**Comment by aedelmann** [comment]
Hi @mena-bosch 
I just tested this feature on dev but it seems that no org.eclipse.vorto released Function blocks are populated in the drop down at Information Model Creation time.

**Comment by mena-bosch** [comment]
@aedelmann did you re-create the index before testing?
This bit of code is dependent on the new search feature, which is itself dependent on re-creating the index, as we discussed last week. 
Not doing so will prevent the search from working appropriately, as it will throw query string queries at fields still indexed as keys rather than text.

**Comment by mena-bosch** [comment]
@aedelmann looks like my search criteria was exactly following the requirements in the description, i.e. _state:Released namespace:org.eclipse.vorto.*_ . As expected, that would only load namespaces from vorto that have a sub-package. Will fix that shortly and replace with _state:Released namespace:org.eclipse.vorto_

**Comment by mena-bosch** [comment]
Btw you might be able to test this in the meantime, by intercepting and tampering with the request. But it won't take long to fix.

**Comment by mena-bosch** [comment]
PR for fix [here](https://github.com/eclipse/vorto/pull/2155).

**Comment by mena-bosch** [comment]
Task for fix [here](https://github.com/eclipse/vorto/issues/2153)

**Comment by mena-bosch** [comment]
I think this is fixed now in the dev machine. @aedelmann let me know if we can close this.

**Comment by aedelmann** [comment]
@mena-bosch 
Awesome :) Works now perfectly.
