### ISSUE TITLE
Exception 500 when invoking generators on Vorto dev system 

### ISSUE THREAD

**Issue by aedelmann** [eclipse/vorto#2168]
Steps taken:
- choose any Information model and go to its details page
- Generate code with any generator
Expected: Generated code can be downloaded successfully
Actual : 500 Internal Error

**Comment by aedelmann** [comment]
Hi @kolotu 
do you have an idea why this is happening ? Might this have sth to do with the caching ?

**Comment by kolotu** [comment]
Hi @aedelmann, 
does this happen for all generators?

**Comment by aedelmann** [comment]
@kolotu 
I tested with all with the same error

**Comment by kolotu** [comment]
I'm pretty sure it has smth to do with the caching. Unfortunately I cannot reproduce it locally yet. I'll look into it.

**Comment by aedelmann** [comment]
Maybe it has sth to do with the missing config for privileged user on dev system. Just an idea

**Comment by kolotu** [comment]
Telling from the logs, it looks like the generator lambda is called, but the generator doesn't respond within 3 seconds, which leads to a timeout and the following exception. So I'd assume that the issue is more related to the generators.

**Comment by kolotu** [comment]
Thanks to @somesh-kumar I've finally found the root cause for this error. The Lambda GeneratorExecutionHandler sets the filename in the Content-Disposition header and adds quotation marks before and after the filename. When deserializing, this is interpreted as an additional quotation mark at the end of the filename (i.e. filename.json" or filename.zip"). That causes the attachment validation in the Vorto Repository to fail.
