### ISSUE TITLE
When searching for a Model by exact name, all models are returned

### ISSUE THREAD

**Issue by w4tsn** [eclipse/vorto#2199]
I noticed when issuing a search request on vorto.eclipse.org with an expression of `ǹame:CoffeeMaker` I get all models of the repository as a result. Only when specifying `name:CoffeeMaker*` I get two results back. Is this intended?

I read in #1833 that the asterisk was only supported at the end and if I understood it correctly also without the asterisk at all. Maybe I'm mistaken here.

What happens?
---

The following query returns all models:

[`https://vorto.eclipse.org/api/v1/search/models?expression=name:CoffeeMaker*`](https://vorto.eclipse.org/api/v1/search/models?expression=name:CoffeeMaker)

What should happen?
---

It should return only one result in the response array. The way it responds now is confusing because the searched model does exist but is not returned in the search. Although this might be a strange search query, if you somehow now or guessed the name of a model.

**Comment by mena-bosch** [comment]
Having a look at this one.

**Comment by mena-bosch** [comment]
Hi @w4tsn, 

  I can replicate your issue on the production repository, only with the HTTP API search.
The Web UI search (which uses the HTTP search behind the scenes) does not replicate it, but neither does it work properly with the `name:` tag. 

At this point I would rather not spend time fixing this, since there is a large improvement in the search already feature-complete and scheduled for milestone 0.13 - see [here](https://github.com/eclipse/vorto/milestone/24?closed=1). 

Among the tickets this search improvement addresses, you will find #1833 as you already mentioned, but also #2046. 

Hopefully you can wait it out until this milestone makes it to production. 

For now, I recommend using the workaround you already found, which is to append a multi-character wildcard `*` at the end of your tagged term.

**Comment by mena-bosch** [comment]
Note: you can play with the new search on our dev environment if you'd like, e.g. [here](https://vorto-dev.eu-central-1.elasticbeanstalk.com/api/v1/search/models?expression=name%3ACoffeeMaker).

**Comment by w4tsn** [comment]
Hey there. Thanks for the response and you looking into this. This is a low-prio from my end so I'm totally fine with waiting for the new search functionality.

Just wanted to make sure this is not by any chance left unnoticed and finds it's way to the new search feature as well.

**Comment by w4tsn** [comment]
Actually this should stay open until it is resolved through deployment of the new version.

**Comment by mena-bosch** [comment]
@w4tsn I agree, let's keep it open and I'll give you a shout when the new search is online.

**Comment by kolotu** [comment]
@mena-bosch this can be closed now, right?

**Comment by mena-bosch** [comment]
@kolotu indeed, the new search is on. 
@w4tsn closing this. Please find the new documentation on search [here](https://github.com/eclipse/vorto/blob/development/repository/repository-elasticsearch/Readme.md). 
Specifically to this issue, an untagged search by model name my return a slightly broader result than a tagged searched by `name:...` - but the issue should be resolved. Also note that model type searches need to be tagged now.
