### ISSUE TITLE
As Collaborator user in somebody else's namespace, I can't delete my account.

### ISSUE THREAD

**Issue by InesTestAccount** [eclipse/vorto#2283]
Only the Dev environment is affected

**Comment by mena-bosch** [comment]
With the new namespace-related refactory, I tried making sure that you can only delete your account if you're not the only administrator of any namespace. 
In other words, here are a few scenarios:

1. User A creates a namespace (meaning they're automatically admin)
2. User A tries to delete their account right away --> cannot because only admin

3. User A creates a namespaces and adds user B as admin
4. User A deletes their account --> OK because it has another admin

5. User B has no namespace, but they're added as admin to user A's
6. User A deletes their account --> OK because user B is admin also
7. User B tries deleting their account --> nope because they are left as the only admin

All other roles should not be relevant - the concept should be that you can only delete the namespaces you own (which happens when you delete your account) if you are not the only admin of any.

**Comment by mena-bosch** [comment]
This said, there could be a bug I haven't noticed yet in the new implementation. Will take a look shortly.

**Comment by mena-bosch** [comment]
Looks fine by me, probably just needed some clarification. @InesTestAccount give us a shout if you find something else - closing for now.
