### ISSUE TITLE
Add Suite Auth Issuer to select in the technical user creation dialogue

### ISSUE THREAD

**Issue by kolotu** [eclipse/vorto#2292]
Also display the issuer in the collaborators table

**Comment by mena-bosch** [comment]
The options available to create technical users are taken agnostically from the options available at logon, with no additional code. 
Obviously the Suite Oauth one is not available at logon, so I suspect it will need to be added programmatically only for that context. 
As discussed, the authentication provider ID is currently only "decorative", insofar as there is no enforcement of a specific authentication provider at logon anyway.

**Comment by mena-bosch** [comment]
Propagating the non-webflow providers (the two versions of suite oauth) to the UI is trivial and I already have the code ready for that. 
My doubt at this point is which picture to associate to the Suite OAuth providers:
- The Bosch ID?
- The OAUth [logo](http://wiki.oauth.net/Logo)? --> in this case, I would need to understand whether it's possible to use a CC BY-SA 3.0 resource in the project and how to properly integrate the license for that resource (e.g. by putting it in a separate folder with the license file in it?)

@kolotu any thoughts?

**Comment by mena-bosch** [comment]
As discussed, will "merge" the two Suite Oauth providers in the presentational layer, since the end-user is agnostic to which version is in use, and we only persist the label as "Bosch IoT Suite OAuth" at this time. 
The icon will be the same as Bosch ID for now, which is already not great for an open source project (but that icon has already been added as a resource to the project by the original devs on 28/6/2019).

**Comment by mena-bosch** [comment]
In addition to the authentication provider ID, I will add the subject (populated only if the technical user flag is true) to the collaborators table.

**Comment by mena-bosch** [comment]
PR [here](https://github.com/eclipse/vorto/pull/2310).

**Comment by mena-bosch** [comment]
merged
