### ISSUE TITLE
Allow consuming HTTP API from other domains

### ISSUE THREAD

**Issue by stheves** [eclipse/vorto#2354]
When using a Javascript client to access the Vorto HTTP API from a host other than vorto.eclipse.org you get the following error in your browser:
`Access to XMLHttpRequest at 'https://vorto.eclipse.org/api/v1/search/models?expression=type:InformationModel%20name:*' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

Could you allow at least these hosts:
- localhost
- *.bosch-iot-suite.com
- *.bosch-iot-cloud.com

**Comment by mena-bosch** [comment]
Had a look. `org.springframework.web.cors.CorsConfiguration` doesn't seem to support wildcards (nor does CORS really), so I'm looking into overloading the functionality to allow that on the bosch-iot... domains. 
@kolotu  I'll push it to the `2354_cors` branch once I have something stable, but I'll need to park this for a while in order to deal with issues in prod.

**Comment by mena-bosch** [comment]
### Status

Presently deployed a solution to dev that:

- Overrides Spring CORS bean by using regex in conjunction with equality checks (so if equality check fails, try interpreting whitelist item as pattern and succeed if matches origin)
- GET, POST, DELETE, PUT and OPTIONS methods allowed

This "works" for normal requests, but pre-flight requests fail, regardless of the fact that OPTIONS is allowed.

This was discovered by @stheves because the `Authorization` header they use for Suite OAuth triggers a preflight request (but they don't need to use it with Vorto as of now - things might change in the future).  

After discussing with @stheves , the current solution is good to go, and we may need to revisit in the future.

**Comment by mena-bosch** [comment]
Fine-tune: working on some additional configuration for headers. 
Worth re-testing on dev with that change before going prod as is.

**Comment by mena-bosch** [comment]
Closing now as this is released.
