### ISSUE TITLE
Uploading models with certain mappings fails to upload

### ISSUE THREAD

**Issue by nagavijays** [eclipse/vorto#237]
Uploading multiple models with mappings fails, returns error message (Status code 502 – Bad Gateway). 

Also, user id is also not recognized when there is error.

**Comment by aedelmann** [comment]
What means "certain" ? Can you please describe that a little bit, in form of:
1) Steps taken (in order to reproduce)
2) Expected result/behaviour
3) Actual result/behaviour

**Comment by laverman** [comment]
Thank you Vijay for creating the issue. I will provide further details.
1) Steps taken
I created 60 Function Blocks and 60 corresponding Mapping files for the target platform LWM2M. Afterwards, I zipped the whole project folder containing both the FBs and their mappings. I accessed the Repository using the web-Ui, logged in and went to the *share* page. I selected the model and clicked on *upload* 

2) Expected result
After checking the models, the modells should have been accepted and I should have been able to check them in, since no model conflicts with models currently in the repository exist (which I checked myself)

3) Actual result
I recieved the described error message: `Status Code: 502 - Bad Gateway`

**Comment by aedelmann** [comment]
Hi Jeroen, 
I could reproduce your problem. 
Firstly, I discovered that one of the mappings could not get parsed due to a keyword clash and therefore grammar validation error. 
I fixed the bug that grammar parsing problems are now showing in the bulk upload result.
Secondly, your mappings have defined the same ID as your functionblocks and therefore could not be uploaded. I also validate this now during bulk upload, meaning whenever the zip file contains files having the same ID as another file in the same zip archive, a validation error is shown in the upload result dialog.

Keep in mind, that the filenames are irrelevant during upload. However the specific full qualified model id (namespace, name and version) as defined in the DSL, has to be unique across other files.

Cheers, Alex
