### ISSUE TITLE
Analyze the replacement of hibernate with EclipseLink

### ISSUE THREAD

**Issue by kolotu** [eclipse/vorto#2389]

**Comment by mena-bosch** [comment]
### Status so far
I've replaced the JPA implementation by doing the following:

1. Excluded hibernate (core and entity manager) from pom.xml where applicable (i.e. where spring-boot-starter-data-jpa was listed as dependency)
2. Added eclipselink in same poms (2.7.7)
3. Added a new config class extending JpaBaseConfiguration and implementing LoadTimeWeavingConfigurer - the latter because using eclipselink's (load-time) weaving fails out of the box and there's very little literature about configuring that. The config exposes an InstrumentationLoadTimeWeaver as a bean, and the getLoadTimeWeaver override returns an instance of ReflectiveLoadTimeWeaver - the latter requires a new spring-context dependency. I am definitely not quite sure this is the right way to go. My general idea was to delegate load-time weaving to spring without having to specify a java agent in the VM params at startup.
4. Replaced some hibernate-specific entity annotations (@NaturalId) with what I believe to be their JPA-neutral equivalent within context (making values unique essentially)

### Conclusions so far

- It seems the application starts and performs normally from a general viewpoint, after the change. 
- However, running clean install with tests enabled takes an outrageously higher amount of time. 
- My first build lasted over an hour, and grinded to a halt with hikari pool logs warning of thread death.
- The fact that Spring is designed to primarily work with hibernate out of the box, and the online literature about swapping with another provider is thin at best, is not reassuring at all. 

### Next steps

- I'll leave the build running for now in hope that it at least concludes, and tells me whether any test breaks because of the change.
- There are two alternative options to move further: 
   1. Merge straight to dev and try some "field" usage (considering we don't really have much in terms of performance monitoring this far)
   2. Or, spend more time investigating how to configure with EclipseLink's own weaving flag on (so far, no LoadTimeWeaver was initialized when activating the option)

**Comment by mena-bosch** [comment]
### Update 
Build still stuck with messages from hikaripool stating thread starvation. Clearly not the right solution yet. 
Will try and figure it out before pushing soon.

**Comment by mena-bosch** [comment]
### Last update for now

New attempt today by removing the LoadTimeWeavingConfigurer dependency, keeping _eclipselink.weaving_ as false and providing an bean-annotated instance of _InstrumentationLoadTimeWeaver_ in the configuration. 
The behavior is similar, but the build aborts due to GC overhead limit exceeded OOM errors preventing late tests from loading the app context. 

Again, the repository seems to run as normal, but that alone is definitely not a good enough indicator. 

My suspicion hasn't changed - the resource issues must have something to do with how load-time weaving is configured, so maybe further options should be considered, e.g. re-activating eclipse's own weaving and figure out how to make it play nice with Spring. 

I will have to park this task for now. 

Pushed the inconclusive experiment to branch [2389](https://github.com/bosch-io/vorto/tree/2389).

**Comment by mena-bosch** [comment]
### Final words

No joy with this, and the replacement caused massive issues with actual data in my local config, in hindsight. 
Closing this and will recommend an exception, due to the fact Spring is clearly designed to work with Hibernate per default, and onlin literature about JPA implementation replacement is not sufficient to go on about this without extensive refactory and testing.
