### ISSUE TITLE
Re-configure @Cacheable repositories

### ISSUE THREAD

**Issue by mena-bosch** [eclipse/vorto#2472]
As discovered by @t-gauss , there is an edge case that prevents programmatic invocations of `find` etc. methods in repositories annotated with `@Cacheable` when starting a Vorto repository from scratch, or in some test contexts. 
This does not replicate when populating the repositories through SQL scripts, but it does when they are populated programmatically, as the `@Cacheable` annotation retains the empty state after population. 

Likely the annotations will be removed in feature #2461, in order to continue adapting the tests. 

This task consists in re-enabling them, but also figuring out a proper cache eviction strategy (considering those 3 tables will be typically written to only once, as they represent "runtime-constant" values).

**Comment by t-gauss** [comment]
This most likely does not work because the CrudRepository methods have different return types but the results are stored in the same cache (findAll returns a set - find only one object). For the repositories were only findAll is invoked in the project we can enable caching only for findAll and evict the corresponding cache on save(). For the other repositories where find or findOne are used as well we might need different caches or configure them in a different way.
