### ISSUE TITLE
Implement SuiteAuth authorization code flow

### ISSUE THREAD

**Issue by kolotu** [eclipse/vorto#2489]
SuiteAuth Authorization Code Flow Tokens contain a user context as Bosch ID. When the authentication with such a token is attempted, the user context should be the one of the Bosch ID user in Vorto.

Validate Token using SuiteAuth
if valid: extract Bosch ID and lookup user
if present: load user context of the Bosch ID user
else: deny access 401

**Comment by mena-bosch** [comment]
Currently not working for me at all on the dev server. 
I am consistently redirected to `https://vorto-dev.eclipse.org/suite/login?error=login+request+denied&error_description=User+not+found.&state=[some state value]` with a HTTP 401
No clue on the root cause and which side the issue sits so far. 
Conversely, Bosch ID login works for me on dev (see comment [here](https://github.com/eclipse/vorto/issues/2475#issuecomment-667153718)).

**Comment by mena-bosch** [comment]
Worth remarking also that the error value: "User+not+found." does not seem to comply with RFC 6749 # section 4.1.2.1 [here](https://tools.ietf.org/html/rfc6749#section-4.1.2.1) if I'm reading it correctly. 
The error occurs both if I am requested to authenticate to the suite (which would succeed with the same credentials outside this context), and if my authenticated session is still running.

**Comment by mena-bosch** [comment]
As discussed separately, there was a defect on the other end preventing random users (including yours truly) from ever logging in. The issue is supposedly resolved on the suite's side (although I can still not log in myself at this time). Will give it some more time and attempts.
