### ISSUE TITLE
NPE on login with github

### ISSUE THREAD

**Issue by hristobojilov** [eclipse/vorto#2590]
`java.lang.NullPointerException: null
        at org.eclipse.vorto.repository.oauth.BoschIDOAuthProvider.createUser(BoschIDOAuthProvider.java:122)`

I have only the github authenticationProvider enabled in my application.yml.

I have the following configuration:
github:
  oauth2:
    enabled: true
    client:
      clientId: whatever
      clientSecret: whatever
      accessTokenUri: https://github.com/login/oauth/access_token
      userAuthorizationUri: https://github.com/login/oauth/authorize
      clientAuthenticationScheme: form
      scope:
         - user:email
    resource:
      userInfoUri: https://api.github.com/user

**Comment by kolotu** [comment]
Hi @hristobojilov  
Have you explicitly disabled the other OAuth providers in the application.yml?
Did you use the Github login option on the UI at <your host>/#/login?

**Comment by hristobojilov** [comment]
Hi @kolotu 
I have just 1 provider enabled which is github.com.
I removed every other provider from the configuration just in case and the problem still persists.
I'm using "Sign in with GitHub" button from the UI login page.
Everything was working fine with version 0.12.6.

**Comment by kolotu** [comment]
@hristobojilov 
Which version are you using? The latest development branch?

**Comment by hristobojilov** [comment]
> 
> 
> @hristobojilov
> Which version are you using? The latest development branch?

Exactly, I was just checking if everything works as expected with it.

**Comment by kolotu** [comment]
@hristobojilov 
Okay, so I'm not able to reproduce the error with the latest development. We are also running the same code base on our [dev environment](https://vorto-dev.eclipse.org) and [production environment](https://vorto.eclipse.org) where the login also works fine, so I would assume that the problem is not caused by the code, but by the configuration. 

If we look at the code, `BoschIDOAuthProvider.java:122` can only be reached, if the `canHandle(Authentication auth)` method at `BoschIDOAuthProvider.java:57` returns true. This can only happen, when the clientId in the `BoschIDOAuthProvider` (`eidp.oauth2.client.clientId`) is equal to the one used in your request. So my guess is that this property `eidp.oauth2.client.clientId` is set to your Github clientId, which it shouldn't. You can set it to any other value, since you're not using it.

In case that also doesn't work for you, you can use a workaround and remove the `@Component` annotation in the `BoschIDOAuthProvider` - this will prevent the OAuth provider from registering in the ApplicationContext.

**Comment by hristobojilov** [comment]
> (`eidp.oauth2.client.clientId`) is equal to the one used in your request. So my guess is that this property `eidp.oauth2.client.clientId`

Your guess is correct. Why do you use this provider is case eidp.oauth2.enabled is false? I believe you should be using it only when it's enabled.

**Comment by kolotu** [comment]
It looks like the enabled properties of the different OAuth2 providers are ignored - I have opened a bug ticket for that https://github.com/eclipse/vorto/issues/2591
