### ISSUE TITLE
Swagger Rest API documentation takes long time to load

### ISSUE THREAD

**Issue by aedelmann** [eclipse/vorto#56]
When accessing http://vorto.eclipse.org/repo/#/api, it takes ~30 seconds to load.

**Comment by aedelmann** [comment]
seems like the swagger-ui.js is quite big in size (couple of MB) which takes quite a bit to download. 
To resolve this, I would suggest to preload it on landing page, where it is not required immediately and has time in the background to be downloaded.

**Comment by aedelmann** [comment]
Alternatively, it should be redistributed as part of the repo.

**Comment by nagavijays** [comment]
Is it possible to use different UI instead of the default. 
Can I suggest https://github.com/Orange-OpenSource/angular-swagger-ui. 
License: MIT
On initial test it took ~11 seconds with 6 REST endpoints. 

Following are the scripts/styles used for testing. Not sure which one has got Eclipse CQ approved. 

<script src="webjars/jquery/2.1.1/jquery.js"></script>
<script src="webjars/bootstrap/3.3.2/js/bootstrap.min.js"></script>
<script type="text/javascript" src="webjars/bootstrap-material-design/0.3.0/js/ripples.min.js"></script>
<script type="text/javascript" src="webjars/bootstrap-material-design/0.3.0/js/material.min.js"></script>
<script type="text/javascript" src="webjars/angularjs/1.3.8/angular.min.js"></script>
<script type="text/javascript" src="webjars/angularjs/1.3.8/angular-route.min.js"></script>
<script type="text/javascript" src="webjars/angularjs/1.3.8/angular-resource.min.js"></script>
<script type="text/javascript" src="webjars/angularjs/1.3.8/angular-sanitize.min.js"></script>
<script type="text/javascript" src="webjars/angular-swagger-ui/0.2.7/dist/scripts/swagger-ui.min.js"></script>

    <link rel="stylesheet" href="webjars/bootstrap/3.3.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="webjars/bootstrap-material-design/0.3.0/css/ripples.min.css">
    <link rel="stylesheet" href="webjars/bootstrap-material-design/0.3.0/css/roboto.min.css">
    <link rel="stylesheet" href="webjars/bootstrap-material-design/0.3.0/css/material.min.css">
    <link rel="stylesheet" href="webjars/angular-swagger-ui/0.2.7/dist/css/swagger-ui.min.css">

See comparison results with current and angular-swagger ui. 

![angular-swagger](https://cloud.githubusercontent.com/assets/13414125/13661377/29a0daba-e6cd-11e5-81dd-2c2c426469f8.PNG)
![swagger-ui](https://cloud.githubusercontent.com/assets/13414125/13661376/29a0699a-e6cd-11e5-9bca-f4578fd87c05.PNG)

**Comment by nagavijays** [comment]
Replaced with angular swagger ui for better responsiveness. 
Created pull request. CQ needs to be created.
