### ISSUE TITLE
Web Editor - Tooltip flickers over the information icon in repository search results

### ISSUE THREAD

**Issue by deepagithub** [eclipse/vorto#619]
**Browser:**  FireFox (_Works fine in Chrome_)
**Steps:**

1. Open an information model from a project
2. Search for any model from the model repository displayed on the right
3. Hover on the i icon

**Expected Result:**

- Tooltip is displayed without flickering

**Actual Result:**

- Tooltip flickers

**Comment by shiv12095** [comment]
The tooltip flickers because the text "Click for details" is large and cannot be rendered properly on the top of the icon, ( the icon is on the edge of the page ).

As an alternative, we can either shorten the text to just "Details". 
This follows the expected behaviour 

<img width="291" alt="screen shot 2017-06-20 at 10 01 18 pm" src="https://user-images.githubusercontent.com/6473226/27344622-9c523084-5604-11e7-9637-7577d3f70855.png">

Or if you want the complete text "Click for details", we can show the tooltip on the left instead.

<img width="297" alt="screen shot 2017-06-20 at 10 07 41 pm" src="https://user-images.githubusercontent.com/6473226/27344725-eafab1de-5604-11e7-8f3f-382a951f7ea1.png">

@deepagithub 
Please provide your suggestion

**Comment by aedelmann** [comment]
Yes please shorten it to "Details".
I would additionally suggest to include the namespace and version in small print. Sometimes duplicate models exist with the same name and the user would not know which to take unless he clicks on the details button. The namespace and version could be below the name of the model in very small print. What do u think ?

**Comment by shiv12095** [comment]
I feel adding the namespace and version might make the row cluttered. Not sure about it, can you please provide a mock up for the row when you want the namespace and version to be included.

Alternatively, we can have a tooltip on top of the model name with the namespace and version.

**Comment by shiv12095** [comment]
The UI has been updated in https://github.com/eclipse/vorto/commit/c3f0173275b766de46f013b846a1050d0c31bcde
