### ISSUE TITLE
A user can drop an entity onto an enum from the vorto repository

### ISSUE THREAD

**Issue by aedelmann** [eclipse/vorto#666]
1) Create enum in eclipse toolset
2) search for entity in model repository
3) Drag and Drop entity on enum

Expected: Error pops up saying "Entities cannot be dropped onto an Enum"
Actual: Entity is imported into enum

**Comment by erlemantos** [comment]
How about this behaviour?

- If a user drops "Model A" from the Repository to any "Model B", "Model A" is ADDED to the project (copied from the Repo). A Reference (using ...) is also added to "Model B" if it legally makes sense.

For example:
- If a user drops "Enum A" from the Repo to "Entity B" in the workspace, "Enum A" is copied to the project, and a Reference is added to "Enum A" in "Entity B".
- If a user drops "Entity A" from the Repo to "Enum B"  in the workspace, "Entity A" is copied to the project, but a Reference to "Entity A" is NOT added to "Enum B" because it doesn't make sense and illegal.

Same applies to function blocks and information models.

Justification:
- Most likely, if a user drags and drops an Entity towards an Enum, the intention might have been to add the Entity to the Project

**Comment by aedelmann** [comment]
@erlemantos 
Sounds good :)
