### ISSUE TITLE
What is category for?

### ISSUE THREAD

**Issue by inno-steffg** [eclipse/vorto#859]
The Vorto DSL specifies a meta-field "category", but I cannot find any explanation what it actually means in documentation and I cannot even see any UI or function that makes use of it.

**Comment by Ebolon** [comment]
Here is a short explanation in the [docs](https://www.eclipse.org/vorto/documentation/appendix/functionblock-dsl-reference.html) for `category`:

Parameter/Element | Mandatory | Description | Type | Examples
-- | -- | -- | -- | --
category | Y | The category should be used to logically group function blocks that semantically belong to the same domain. | top level category (mandatory) and a sub category (optional), separated by aslash (/) | IAP/smarthome</br>indego

---

The DSL allows to define `category` as:

_Terminals.xtext_
`terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;`

_Functionblock.xtext_
`CATEGORY : ID ('/' ID)*;`

---
Currently there is no model published which makes use of this feature. I think the same can be possible archived with the namespace of a model. Maybe `category` is something legacy because Vorto 0.1 did not supported namespaces as today.

Here some fun stats what categories are currently used in the vorto repository:
```
category: count
----------------
iot : 157
demo : 221
sensors : 8
None : 162
payloadmapping : 100
example : 13
eclipse : 3
SmartObject : 80
IoT : 1
general : 4
main : 1
Activity : 1
xdk : 3
devices : 1
umgebungskachel : 5
```

**Comment by inno-steffg** [comment]
Super summary.

Now, when it is used that "strange", why not making it optional everywhere? It is so already in Datatype and Mapping, but mandatory in Function Block and Information Model.
Making it optional there wouldn't break existing definitions, but would simplify definitions and eventually increase the specifiers experience.

I was distracted by that detail, seeing it being required, caused me to search for the sense to put something meaningful in it.

Regards
Steffen
