### ISSUE TITLE
Operations cannot use Dictionary type

### ISSUE THREAD

**Issue by e-grigorov** [eclipse/vorto#907]
I am trying to model a single property where the value can be managed with a setter and getter:
```
	status{
		mandatory dic as Dictionary 
	}
	operations{
		getDic() returns Dictionary
		setDic(dic as Dictionary)
	}
```
The property definition seems ok but there are errors on the operations:
* mismatched input 'as' expecting '('
* no viable alternative at input 'dic'
* no viable alternative at input 'Dictionary'

Is my example correct or I am missing something?

My initial expectation is that the property type, operation result and operation argument are using the same set of types.

**Comment by aedelmann** [comment]
Hi @e-grigorov 
seems to be a bug. That should work. Classifying your issue as 'bug'. 
Thanks.

**Comment by aedelmann** [comment]
Seems to be cleaner but I’m not sure if this change would cause the autocompletion not to work anymore. You can try it out.

**Comment by Ebolon** [comment]
I tried it to change the DSL to my suggestion in https://github.com/Ebolon/vorto/tree/simple-ops. It did not work out as expected. Especially l do not feel comfortable because multiple generators are using this feature and no unit tests existing. For now I would say it is better to introduce a `ReturnDictonaryType`. I will have a look into this later.
